### ISSUE TITLE
Getting Error NoClassDefinationFound

### ISSUE THREAD

**Issue by chnouman** [facebook/rebound#88]
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.dixeam.millionarequotes, PID: 20997                                                   java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/rebound/SpringSystem; 
at com.dixeam.millionarequotes.utils.RecyclerViewAnimator.<init>(RecyclerViewAnimator.java:51)                                                                                 at com.dixeam.millionarequotes.Recent$SimpleStringRecyclerViewAdapter.<init>(Recent.java:155)                                                                                 at com.dixeam.millionarequotes.Recent.setupRecyclerView(Recent.java:68)                                                                                 at com.dixeam.millionarequotes.Recent.onCreateView(Recent.java:53)

Please help me.

**Comment by francescobonni** [comment]
I have the same problem when change compile 'com.facebook.rebound:rebound:0.3.8' in implementation 'com.facebook.rebound:rebound:0.3.8'
